#!/bin/bash
# Build phase hook for Docker Hub automated builds
#
# Expects DISTRO and TEXLIVE_VERSION
#
# Orinally based on https://github.com/vaidik/docker-etcd/

set -e

source common.sh
source hooks/util.sh


name="mjenz/texlive:$DISTRO"
if [ -n "$TEXLIVE_VERSION" ]; then
    name="$name-vanilla-$TEXLIVE_VERSION"
fi

if [ "$GITHUB_EVENT_NAME" = "push" ]; then
    # Pull previous image to speed up build, but do clean builds for "schedule" events.
    # See https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/
    # for --cache-from explanation.
    trace docker pull "$name-full" || true
fi

build () {
    trace docker build --cache-from "$name-full" \
        --build-arg "BASE_IMAGE=ubuntu:$DISTRO" \
        --build-arg "TEXLIVE_VERSION=$TEXLIVE_VERSION" \
        "$@"
}

# Build the base image, and tag for vanilla images
build -t base --target base .

if [ -z "$TEXLIVE_VERSION" ]; then
    # Build $DISTRO-minimal, $DISTRO, and $DISTRO-full
    build -t "$name-minimal" --target minimal .
    build -t "$name" --target default .
    build -t "$name-full" --target full .
    print_versions "$name-minimal"
    print_versions "$name"
    print_versions "$name-full"
else
    # Build $DISTRO-vanilla-$year and $DISTRO-vanilla-$year-full using tagged base image
    build -f Dockerfile.vanilla -t "$name" --target basic .
    build -f Dockerfile.vanilla -t "$name-full" --target full .
    print_versions "$name"
    print_versions "$name-full"
fi
