#!/bin/bash
# Build phase hook for Docker Hub automated builds
# Based on https://github.com/vaidik/docker-etcd/

set -e

source hooks/util.sh

trace env

build() {
	trace docker build -t "mjenz/texlive:$TAG" \
		--build-arg BASE_IMAGE=$BASE_IMAGE \
		--build-arg TEXLIVE_VERSION=$TEXLIVE_VERSION \
		.
}

# Run build() once for each set of variables in matrix.sh
while read -r line; do
    eval "$line build"
done < <(hooks/matrix.sh)
