#!/bin/bash
# Push phase hook for Docker Hub automated builds
# Based on https://github.com/vaidik/docker-etcd/

set -e

source common.sh
source hooks/util.sh

# Manually tag latest if possible
trace docker tag "mjenz/texlive:$LATEST_UBUNTU" "mjenz/texlive:latest" || true
trace docker tag "mjenz/texlive:$LATEST_UBUNTU-vanilla-$LATEST_TEXLIVE" "mjenz/texlive:vanilla" || true
trace docker images mjenz/texlive

# Push every image
for i in $(docker images mjenz/texlive --format "{{.Repository}}:{{.Tag}}"); do
    if [[ $i != *"<none>" ]]; then
        # Somehow Docker Hub ends up with mjenz/texlive:<none> and then explodes
        # if you touch it
        trace docker push "$i"
    fi
done
