name: Build Docker images

on:
  push:
  schedule:
    # Every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [xenial, bionic, focal]
        texlive_version: ['', 2019, 2020]
    env:
        DISTRO: ${{ matrix.distro }}
        TEXLIVE_VERSION: ${{ matrix.texlive_version }}
    steps:
    - run: env | sort
    - uses: actions/checkout@v2
    - run: hooks/build
    - uses: azure/docker-login@v1
      with:
        username: mjenz
        password: ${{ secrets.DOCKERIO_PASSWORD }}
    - run: hooks/push
